#!/usr/bin/env bash

while true; do
	printf "\n>>>   Is this arch OS installation hosted in VM [N]: "
	read -r is_vm
	is_vm=${is_vm:-N}

	case $is_vm in
		[yY][eE][sS]|[yY])
			printf ">>>   Installing VM requirements\n"
			sudo pacman -S --noconfirm xf86-input-vmmouse xf86-video-vmware mesa
			break
		;;
		[nN][oO]|[nN])
			printf ">>>   Installing bluetooth, sound and Intel graphics drivers\n"
			sudo pacman -S --noconfirm bluez bluez-utils alsa-utils mesa
			break
		;;
		*)
			echo ">>>   Invalid input... Valid entries are E.g. [Y / N] or [y / n] or [Yes / No]"
		;;
	esac
done

printf ">>>   Installing xorg\n"
sudo pacman -S --noconfirm xorg xorg-server

printf ">>>   Installing Gnome and a few extra apps\n"
sudo pacman -S --noconfirm gnome gnome-tweaks gnome-usage gnome-nettool dconf-editor

printf ">>>   Enabling GDM\n"
sudo systemctl enable gdm.service

printf ">>>   Your setup is ready. You can reboot now!\n"
